### ISSUE TITLE
[FASE-3] Desenvolvimento do Modelo de Classificação

### ISSUE THREAD

**Issue by product-as-service** [product-as-service/Desafio-Produto#3]
## Objetivo
**Desenvolvimento do Modelo de Classificação**

**Pessoas envolvidas**: 
- Engenharia Analytics

### **O que:**

Criação do modelo de machine learning :squirrel:

___
### **Por que?**

Agregar valor ao usuário priorizando empresas ativas em funcionamento

___
### Obrigatórios:
- [ ] Estabelecimento de 3 classificações, Baixa, Média e Alta probabilidade de ser ativo. [Tarefa Link](https://github.com/product-as-service/Desafio-Produto/issues/5) https://github.com/product-as-service/Desafio-Produto/issues/5
- [ ] Criação de uma taxa de confiança para a classificação Gerada [Tarefa Link](https://github.com/product-as-service/Desafio-Produto/issues/6) https://github.com/product-as-service/Desafio-Produto/issues/6
- [ ] Definir formas de retroalimentação do modelo(rota de feedback?) [Tarefa Link](https://github.com/product-as-service/Desafio-Produto/issues/7) https://github.com/product-as-service/Desafio-Produto/issues/7

### Desejáveis:
- [ ] Opção de não prever / Remoção de Outliers
- [ ] Busca de projetos Open source que resolvem problemas semelhantes ([kaggle](https://www.kaggle.com/))
